t<-seq(0,30,2)
func<-function(K,n,r)
{K/(1+((K/n)-1)*exp(-r*t)) }
value<-func(30,20,0.5)
par(mfrow=c(2,1))
plot(t,value,pch=10,col.lab="red",cex=1.5,xlab="В¬рем€",ylab="„исленность попул€ции",type="b",col="darkblue")
legend("right", inset=.05, legend="„исленность попул€ции ~ ¬рем€",lty=1, pch=10, col="darkblue")
set.seed(100)
Gauss<-rnorm(value,0,0.5)
plot(t,value1,pch=20,col.lab="red",cex=1.5,xlab="¬рем€",ylab="„исленность попул€ции",type="l")
points(t,round(value+Gauss),col="darkblue",cex=1.5,pch=20)
legend("right", inset=.05, legend="„исленность попул€ции ~ √ауссов шум",lty=1, pch=20,col="darkblue")